### ISSUE TITLE
update filters

### ISSUE THREAD

**Issue by laurentleseigneur** [bonitasoft/bonita-admin-application#28]
hi,

I would like to have filters & sort to identify cases with failures, open & healthy
thanks

![image](https://user-images.githubusercontent.com/6574899/132387662-9e4db629-a694-48cd-af28-0d21e8874744.png)

**Comment by DumitruCorini** [comment]
Hello, Laurent, you can find those informations inside the Admin Case list of the Application.
I don't think we have planned to re-implement those inside this page as well. 
If you really want to have those, you can always modify the page yourself, rebuild it and re-deploy it.
The code for the page is currently private, but since you are part of the organization, you should be able to see it. 
The page can be found here: https://github.com/bonitasoft/bonita-portal-js-sp/tree/master/subscription/main/features-sp/admin/monitoring
To rebuild it: just run `mvn clean install`
To redeploy it: replace the portal.js folder that you can find inside the `bonita` folder with the one from inside the `target/bonita-portal-js-...` (that's inside the git repository).
And you will have your changes.
